var express = require("express");
var app = express();
var cors = require("cors");
const bodyParser = require("body-parser");

app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

const formidable = require("formidable");
const cloudinary = require("cloudinary");
require("dotenv").config();

const { GoogleSpreadsheet } = require("google-spreadsheet");
let doc = "";

async function accessSpreadsheet() {
  doc = new GoogleSpreadsheet(process.env.SHEET_ID);
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  });

  await doc.loadInfo();
}

cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.API_KEY,
  api_secret: process.env.API_SECRET,
});

app.post("/upload", function (req, res) {
  const form = formidable({ multiples: false });

  form.parse(req, (err, fields, file) => {
    if (err) {
      next(err);
      return;
    }

    cloudinary.v2.uploader.upload(
      file.file.filepath,
      fields,
      function (error, result) {
        if (result) {
          res.status(200).send({ response: result });
        }
      }
    );
  });
});

app.get("/get-files", function (req, res) {
  cloudinary.v2.api.resources_by_tag(
    "portfolio",
    { resource_type: "video" },
    function (error, result) {
      if (result) {
        res.status(200).send({ response: result });
      }
    }
  );
});

app.post("/add-message", async function (req, res) {
  await accessSpreadsheet();
  const sheet = doc.sheetsByIndex[0];
  let data = req.body;
  data.date = new Date();
  const result = sheet.addRow(data);
  res.status(200).send({ response: result });
});

const port = process.env.PORT || 8000;

app.listen(port, function () {
  console.log("Example app listening on port 8000.");
});
